{% set version = "24.12.0" %}
{% set test_skips = "custom_specification or default_context or default_templates or templating_dir" %}

package:
  name: sanic-ext
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sanic-ext/sanic_ext-{{ version }}.tar.gz
  sha256: 8f912f4c29f242bc638346d09b79f0c8896ff64e79bd0e7fa09eac4b6c0e23c8

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pyyaml >=3.0.0

test:
  source_files:
    - tests
  imports:
    - sanic_ext
  commands:
    - pip check
    - coverage run --source=sanic_ext --branch -m pytest -vv --tb=long --color=yes -k "not ({{ test_skips }})"
    - coverage report --show-missing --skip-covered --fail-under=81
  requires:
    - jinja2
    - pip
    - pytest-asyncio
    - pytest-cov
    - sanic-testing
    # extra test deps declared in tox.ini
    - attrs
    - msgspec
    - pydantic <2
    - sanic
    - python {{ python_min }}

about:
  home: http://github.com/sanic-org/sanic-ext
  summary: Extend your Sanic installation with some core functionality.
  license: MIT
  license_file: LICENSE
  doc_url: https://sanic.dev/en/plugins/sanic-ext/getting-started.html

extra:
  recipe-maintainers:
    - bollwyvl
