{% set version = "23.12.0" %}

package:
  name: sanic-ext
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sanic-ext/sanic-ext-{{ version }}.tar.gz
  sha256: 42fc41e7fafa58f3b790f685f3dd8a8de281460b4169d0e91f4e11b8747f845c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyyaml >=3.0.0

test:
  source_files:
    - tests
  imports:
    - sanic_ext
  commands:
    - pip check
    - pytest -vv --cov=sanic_ext --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not (custom_specification or default_context or default_templates or templating_dir)" --cov-fail-under=81
  requires:
    - jinja2
    - pip
    - pytest-asyncio
    - pytest-cov
    - sanic-testing
    # extra test deps declared in tox.ini
    - attrs
    - msgspec
    - pydantic <2
    - sanic
    - python {{ python_min }}

about:
  home: http://github.com/sanic-org/sanic-ext
  summary: Extend your Sanic installation with some core functionality.
  license: MIT
  license_file: LICENSE
  doc_url: https://sanic.dev/en/plugins/sanic-ext/getting-started.html

extra:
  recipe-maintainers:
    - bollwyvl
