{% set version = "23.3.0" %}

package:
  name: sanic-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sanic-ext/sanic-ext-{{ version }}.tar.gz
  sha256: 73c8b21061211cbfa8beb282b1cb052ec10033f3ab02fff854482b52bace5a4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pyyaml >=3.0.0

test:
  source_files:
    - tests
  imports:
    - sanic_ext
  commands:
    - pip check
    - pytest -vv --cov=sanic_ext --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not (custom_specification or default_templates or templating_dir)" --cov-fail-under=81
  requires:
    - jinja2
    - pip
    - pytest-asyncio
    - pytest-cov
    - sanic-testing
    # extra test deps declared in tox.ini
    - attrs
    - pydantic
    - sanic

about:
  home: http://github.com/sanic-org/sanic-ext
  summary: Extend your Sanic installation with some core functionality.
  license: MIT
  license_file: LICENSE
  doc_url: https://sanic.dev/en/plugins/sanic-ext/getting-started.html

extra:
  recipe-maintainers:
    - bollwyvl
