# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 24.12.0
  # see https://github.com/sanic-org/sanic-ext/blob/v24.12.0/sanic_ext/bootstrap.py#L42C15-L42C25
  sanic_min: 21.3.2

package:
  name: sanic-ext
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sanic-ext/sanic_ext-${{ version }}.tar.gz
  sha256: 8f912f4c29f242bc638346d09b79f0c8896ff64e79bd0e7fa09eac4b6c0e23c8
  patches:
    - 0000-no-test-site-packages.diff

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools <60
  run:
    - python >=${{ python_min }}
    - pyyaml >=3.0.0
  run_constraints:
    - sanic >=${{ sanic_min }}

tests:
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
    requirements:
      run:
        - attrs
        - jinja2
        - msgspec
        - pip
        - pydantic <2
        - pytest-asyncio
        - pytest-cov
        - python ${{ python_min }}.*
        - sanic
        - sanic-testing
    script:
      - pip check
      - python run_test.py

about:
  summary: Extend your Sanic installation with some core functionality.
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/sanic-org/sanic-ext
  documentation: https://sanic.dev/en/plugins/sanic-ext/getting-started.html

extra:
  recipe-maintainers:
    - bollwyvl
